import { cancelOrder, Execute } from '@reservoir0x/client-sdk'
import useUserAsks from 'hooks/useUserAsks'
import React, { FC, useState } from 'react'
import { useSigner } from 'wagmi'
import * as Dialog from '@radix-ui/react-dialog'
import { CgSpinner } from 'react-icons/cg'
import ModalCard from './ModalCard'
import Error from './Error'
import useIsWrongNetwork from 'hooks/useIsWrongNetwork'

// Load environment variables using the appropiate Next.js
// nomenclature
// https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser
const API_BASE = process.env.NEXT_PUBLIC_API_BASE

type Props = {
  orders: ReturnType<typeof useUserAsks>
}

const Cancel: FC<Props> = ({ orders }) => {
  // wagmi hooks
  const [{ data: signer }] = useSigner()

  // Check if the user is connected to the wrong Ethereum Network
  const isWrongNetwork = useIsWrongNetwork()

  // Steps are shown in the modal to inform user about the
  // progress of execution for the current action.
  // The steps variable will be updated by the client SDK
  const [steps, setSteps] = useState<Execute['steps']>()

  // Loading state for the action button
  const [waitingTx, setWaitingTx] = useState<boolean>(false)

  // Error state for the action button
  const [error, setError] = useState<any>(undefined)

  // Control the open state for the modal
  const [open, setOpen] = useState(false)

  // Extract the order ID from the response
  const id = orders.data?.orders?.[0]?.id
  // Extract the order maker from the response
  const maker = orders.data?.orders?.[0]?.maker

  // Close the modal and reset parameters
  const close = () => {
    // Close modal
    setOpen(false)
    // Reset steps
    setSteps(undefined)
    // Toggle off waiting state
    setWaitingTx(false)
  }

  // Execute the following function when the transaction has been
  // completed sucessfully
  const handleSuccess: Parameters<
    typeof cancelOrder
  >[0]['handleSuccess'] = () => {
    // Refetch data from `/orders/asks/v1`
    orders && orders.mutate()
    // Remove the error message, if any
    setError(undefined)
  }

  // Execute the following function when the transaction has been
  // failed
  const handleError: Parameters<typeof cancelOrder>[0]['handleError'] = (
    err: any
  ) => {
    // Close the steps modal
    close()

    if (err?.code !== 4001) {
      // Set the error message in the UI
      setError(
        <Error>
          No listing found. List Reservoir 721 for sale and try again.
        </Error>
      )
    }
  }

  // Execute this function to cancel an user's listing
  // order
  const execute = async (id: string, maker: string) => {
    // Set the loading state on
    setWaitingTx(true)

    await cancelOrder({
      query: {
        id, // The order ID
        maker, // The order maker
      },
      // Signer is an Ethereum signer object, usually generated by the browser
      signer,
      // The API base url for reservoir
      apiBase: API_BASE,
      setState: setSteps,
      handleSuccess,
      handleError,
    })

    // Set the loading state off
    setWaitingTx(false)
  }

  const listingExists = orders.data && id

  return (
    <article>
      {error}
      {/* Use Radix UI to create a modal to display the current state */}
      {/* of execution for the chosen transaction */}
      <Dialog.Root open={open} onOpenChange={setOpen}>
        <Dialog.Trigger
          disabled={isWrongNetwork || waitingTx || !signer || !listingExists}
          onClick={() => maker && id && execute(id, maker)}
          className="btn-primary-fill w-[222px] mx-auto"
        >
          {waitingTx ? (
            <CgSpinner className="h-4 w-4 animate-spin" />
          ) : (
            'Cancel Listing'
          )}
        </Dialog.Trigger>
        <Dialog.Portal>
          <Dialog.Overlay>
            <ModalCard
              loading={waitingTx}
              title="Cancel Listing"
              close={close}
              steps={steps}
            />
          </Dialog.Overlay>
        </Dialog.Portal>
      </Dialog.Root>
    </article>
  )
}

export default Cancel
